// <auto-generated />
using System;
using ClubCore.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClubProcessor.Migrations.CompetitorDb
{
    [DbContext(typeof(CompetitorDbContext))]
    [Migration("20251109145612_AddLeaguePropertyToCompetitor")]
    partial class AddLeaguePropertyToCompetitor
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("ClubProcessor.Models.Competitor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AgeGroup")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClaimStatus")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClubNumber")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("GivenName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsFemale")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastUpdatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("League")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("VetsBucket")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Competitors");
                });
#pragma warning restore 612, 618
        }
    }
}
