// <auto-generated />
using System;
using ClubCore.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClubProcessor.Migrations.EventDb
{
    [DbContext(typeof(EventDbContext))]
    [Migration("20251024193638_AddCalendarEventsTable")]
    partial class AddCalendarEventsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("ClubData.Models.CalendarEvent", b =>
                {
                    b.Property<int>("EventID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCancelled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsClubChampionship")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEvening10")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsHardRideSeries")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsNonStandard10")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<double>("Miles")
                        .HasColumnType("REAL");

                    b.Property<string>("SheetName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("TEXT");

                    b.HasKey("EventID");

                    b.ToTable("CalendarEvents", (string)null);
                });

            modelBuilder.Entity("ClubProcessor.Models.Ride", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActualTime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("AvgSpeed")
                        .HasColumnType("REAL");

                    b.Property<int?>("ClubNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Eligibility")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EventNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HCAdjustedTime")
                        .HasColumnType("TEXT");

                    b.Property<int?>("HCRank")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HandicapGenerated")
                        .HasColumnType("TEXT");

                    b.Property<string>("HandicapUsed")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRoadBike")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PointsAwarded")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StandardTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("TimeDelta")
                        .HasColumnType("TEXT");

                    b.Property<double>("TotalSeconds")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Rides");
                });
#pragma warning restore 612, 618
        }
    }
}
