// <auto-generated />
using System;
using ClubCore.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClubProcessor.Migrations.EventDb
{
    [DbContext(typeof(EventDbContext))]
    [Migration("20260203174901_AddRoundRobinClubFromYear")]
    partial class AddRoundRobinClubFromYear
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.11");

            modelBuilder.Entity("ClubCore.Models.CalendarEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("EventNumber")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCancelled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsClubChampionship")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEvening10")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsHardRideSeries")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsHillClimb")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsNonStandard10")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRoundRobinEvent")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<double>("Miles")
                        .HasColumnType("REAL");

                    b.Property<string>("RoundRobinClub")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EventNumber")
                        .IsUnique();

                    b.ToTable("CalendarEvents", (string)null);
                });

            modelBuilder.Entity("ClubCore.Models.PointsAllocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Points")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("PointsAllocations");
                });

            modelBuilder.Entity("ClubCore.Models.Ride", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double?>("AvgSpeed")
                        .HasColumnType("REAL");

                    b.Property<int?>("ClubNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EventEligibleRidersRank")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EventEligibleRoadBikeRidersRank")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EventNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EventRank")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EventRoadBikeRank")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRoadBike")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("JuniorsPoints")
                        .HasColumnType("REAL");

                    b.Property<int?>("JuniorsPosition")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("JuvenilesPoints")
                        .HasColumnType("REAL");

                    b.Property<int?>("JuvenilesPosition")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("LeaguePoints")
                        .HasColumnType("REAL");

                    b.Property<int?>("LeaguePosition")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<double?>("NevBrooksPoints")
                        .HasColumnType("REAL");

                    b.Property<int?>("NevBrooksPosition")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("NevBrooksSecondsAdjustedTime")
                        .HasColumnType("REAL");

                    b.Property<double?>("NevBrooksSecondsApplied")
                        .HasColumnType("REAL");

                    b.Property<double?>("NevBrooksSecondsGenerated")
                        .HasColumnType("REAL");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<double?>("RoadBikeMenPoints")
                        .HasColumnType("REAL");

                    b.Property<int?>("RoadBikeMenPosition")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("RoadBikeWomenPoints")
                        .HasColumnType("REAL");

                    b.Property<int?>("RoadBikeWomenPosition")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RoundRobinClub")
                        .HasColumnType("TEXT");

                    b.Property<double?>("RoundRobinPoints")
                        .HasColumnType("REAL");

                    b.Property<int?>("RoundRobinPosition")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("RoundRobinWomenPoints")
                        .HasColumnType("REAL");

                    b.Property<int?>("RoundRobinWomenPosition")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("SeniorsPoints")
                        .HasColumnType("REAL");

                    b.Property<int?>("SeniorsPosition")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("TotalSeconds")
                        .HasColumnType("REAL");

                    b.Property<double?>("VeteransHandicapSeconds")
                        .HasColumnType("REAL");

                    b.Property<double?>("VeteransPoints")
                        .HasColumnType("REAL");

                    b.Property<int?>("VeteransPosition")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("WomenPoints")
                        .HasColumnType("REAL");

                    b.Property<int?>("WomenPosition")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Rides");
                });

            modelBuilder.Entity("ClubCore.Models.RoundRobinClub", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FromYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WebsiteUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("RoundRobinClubs");
                });

            modelBuilder.Entity("ClubCore.Models.RoundRobinRider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFemale")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RoundRobinClub")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("RoundRobinRiders");
                });
#pragma warning restore 612, 618
        }
    }
}
