// <auto-generated />
using ClubProcessor.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClubProcessor.Migrations.EventDb
{
    [DbContext(typeof(EventDbContext))]
    partial class EventDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("ClubProcessor.Models.Ride", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActualTime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("AvgSpeed")
                        .HasColumnType("REAL");

                    b.Property<int?>("ClubNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Eligibility")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EventNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HCAdjustedTime")
                        .HasColumnType("TEXT");

                    b.Property<int?>("HCRank")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HandicapGenerated")
                        .HasColumnType("TEXT");

                    b.Property<string>("HandicapUsed")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRoadBike")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PointsAwarded")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StandardTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("TimeDelta")
                        .HasColumnType("TEXT");

                    b.Property<double>("TotalSeconds")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Rides");
                });
#pragma warning restore 612, 618
        }
    }
}
