name: Generate Static Site

permissions:
  actions: read
  contents: write
  pull-requests: write

on:
  workflow_dispatch:
    inputs:
      year:
        description: "Year to process (e.g. 2026)"
        required: true

  workflow_run:
    workflows: ["Process Club Data"]
    types:
      - completed

jobs:
  debug-event:
    runs-on: ubuntu-latest
    steps:
      - name: Dump workflow_run payload
        run: echo "${{ toJson(github.event.workflow_run) }}"

  generate-site:
    needs: debug-event
    uses: ./.github/workflows/_site-core.yml
    with:
      year: ${{ github.event.inputs.year || github.event.workflow_run.jobs.build-test-run.outputs.year }}
    secrets:
      roundrobin_pat: ${{ secrets.ROUNDROBIN_PAT }}
